const id = (path: string) => (entityId: string): string => `${path}/${entityId}`

export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh-token',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    me: '/auth/me',
    changePassword: '/auth/change-password',
  },
  users: {
    list: '/users',
    byId: id('/users'),
    profile: (userId: string) => `/users/${userId}/profile`,
    search: '/users/search',
    active: '/users/active',
    inactive: '/users/inactive',
    deactivate: (userId: string) => `/users/${userId}/deactivate`,
    reactivate: (userId: string) => `/users/${userId}/reactivate`,
  },
  employees: {
    list: '/employees',
    byId: id('/employees'),
    employmentHistory: (employeeId: string) => `/employees/${employeeId}/employment-history`,
    promote: (employeeId: string) => `/employees/${employeeId}/promote`,
    transfer: (employeeId: string) => `/employees/${employeeId}/transfer`,
    byDepartment: (departmentId: string) => `/employees/by-department/${departmentId}`,
    byManager: (managerId: string) => `/employees/by-manager/${managerId}`,
    active: '/employees/active',
    resigned: '/employees/resigned',
  },
  departments: { list: '/departments', byId: id('/departments'), employees: (d: string) => `/departments/${d}/employees` },
  positions: { list: '/positions', byId: id('/positions') },
  attendance: {
    checkIn: '/attendance/check-in',
    checkOut: '/attendance/check-out',
    list: '/attendance',
    byId: id('/attendance'),
    byEmployee: (e: string) => `/attendance/${e}`,
    today: '/attendance/today',
    range: '/attendance/range',
    summary: (e: string) => `/attendance/summary/${e}`,
  },
  leave: {
    list: '/leaves',
    apply: '/leaves/apply',
    byId: id('/leaves'),
    approve: (l: string) => `/leaves/${l}/approve`,
    reject: (l: string) => `/leaves/${l}/reject`,
    cancel: (l: string) => `/leaves/${l}/cancel`,
    balance: (e: string) => `/leaves/balance/${e}`,
    pending: '/leaves/pending',
    history: (e: string) => `/leaves/history/${e}`,
  },
  payroll: {
    list: '/payroll',
    byId: id('/payroll'),
    generate: '/payroll/generate',
    run: '/payroll/run',
    slips: (e: string) => `/payroll/slips/${e}`,
    summary: '/payroll/summary',
    history: '/payroll/history',
  },
  compensation: {
    list: '/compensation',
    byId: id('/compensation'),
    byEmployee: (e: string) => `/compensation/${e}`,
    adjust: (e: string) => `/compensation/${e}/adjust`,
    salaryStructures: '/salary-structures',
  },
  timeTracking: {
    list: '/time-logs',
    byId: id('/time-logs'),
    start: '/time-logs/start',
    stop: '/time-logs/stop',
    byEmployee: (e: string) => `/time-logs/${e}`,
    today: (e: string) => `/time-logs/today/${e}`,
  },
  recruitment: {
    list: '/recruitment/jobs',
    byId: id('/recruitment/jobs'),
    jobs: '/recruitment/jobs',
    job: id('/recruitment/jobs'),
    applicants: '/recruitment/applicants',
    applicant: id('/recruitment/applicants'),
    scheduleInterview: (a: string) => `/recruitment/applicants/${a}/schedule-interview`,
    hire: (a: string) => `/recruitment/applicants/${a}/hire`,
    reject: (a: string) => `/recruitment/applicants/${a}/reject`,
  },
  interviews: {
    list: '/interviews',
    byId: id('/interviews'),
    reschedule: (i: string) => `/interviews/${i}/reschedule`,
    complete: (i: string) => `/interviews/${i}/complete`,
  },
  performance: {
    list: '/performance/reviews',
    byId: id('/performance/reviews'),
    reviews: '/performance/reviews',
    review: id('/performance/reviews'),
    submit: (r: string) => `/performance/reviews/${r}/submit`,
    approve: (r: string) => `/performance/reviews/${r}/approve`,
    ratings: (e: string) => `/performance/ratings/${e}`,
  },
  organization: {
    list: '/org/chart',
    byId: (id: string) => `/org/chart/${id}`,
    chart: '/org/chart',
    reportingLines: '/org/reporting-lines',
    positionsTree: '/org/positions-tree',
  },
  documents: {
    upload: '/documents/upload',
    list: '/documents',
    byId: id('/documents'),
    byEmployee: (e: string) => `/documents/employee/${e}`,
  },
  notifications: {
    list: '/notifications',
    markRead: '/notifications/mark-read',
    markAllRead: '/notifications/mark-all-read',
    byId: id('/notifications'),
  },
  roles: {
    list: '/roles',
    byId: id('/roles'),
    permissions: '/permissions',
    rolePermissions: (r: string) => `/roles/${r}/permissions`,
  },
  audit: {
    list: '/audit-logs',
    byId: id('/audit-logs'),
    byEntity: (entity: string, entityId: string) => `/audit-logs/${entity}/${entityId}`,
    byUser: (userId: string) => `/audit-logs/user/${userId}`,
  },
  reports: {
    list: '/reports/employees',
    byId: id('/reports'),
    employees: '/reports/employees',
    attendance: '/reports/attendance',
    payroll: '/reports/payroll',
    leaveUsage: '/reports/leave-usage',
    turnover: '/reports/turnover',
  },
  analytics: { dashboard: '/analytics/dashboard' },
  settings: {
    list: '/settings',
    byId: id('/settings'),
    root: '/settings',
    company: '/settings/company',
    leaveTypes: '/settings/leave-types',
  },
  tenants: {
    list: '/tenants',
    byId: id('/tenants'),
    suspend: (t: string) => `/tenants/${t}/suspend`,
    reactivate: (t: string) => `/tenants/${t}/reactivate`,
  },
  billing: {
    list: '/billing/invoices',
    byId: id('/billing/invoices'),
    subscription: '/billing/subscription',
    subscribe: '/billing/subscribe',
    cancel: '/billing/cancel',
    invoices: '/billing/invoices',
    paymentMethods: '/billing/payment-methods',
  },
  system: {
    list: '/health',
    byId: id('/health'),
    health: '/health',
    metrics: '/metrics',
    status: '/status',
    version: '/version',
  },
} as const
